"""
services/report_service.py
-----------------------------
Assembles the final structured report (Module 16) from everything stored
for a document, computes the overall risk summary, and can render a
downloadable PDF version.

Dependencies: SQLAlchemy, fpdf2 (add to requirements.txt if PDF export is enabled)
"""

from models.document import Document
from models.analysis import ExtractedInformation, VerificationResult, RiskAnalysis

RISK_ORDER = {"LOW": 0, "MEDIUM": 1, "HIGH": 2}


def compute_overall_risk(risks: list[RiskAnalysis]) -> tuple[str, dict]:
    counts = {"LOW": 0, "MEDIUM": 0, "HIGH": 0}
    for r in risks:
        counts[r.risk_level] = counts.get(r.risk_level, 0) + 1

    if counts["HIGH"] > 0:
        overall = "HIGH"
    elif counts["MEDIUM"] > 0:
        overall = "MEDIUM"
    elif counts["LOW"] > 0:
        overall = "LOW"
    else:
        overall = "LOW"
    return overall, counts


def build_report(document_id: str) -> dict:
    document = Document.query.get(document_id)
    extracted = ExtractedInformation.query.filter_by(document_id=document_id).first()
    verifications = VerificationResult.query.filter_by(document_id=document_id).all()
    risks = RiskAnalysis.query.filter_by(document_id=document_id).all()

    overall_risk, counts = compute_overall_risk(risks)

    return {
        "document_summary": document.to_dict() if document else {},
        "extracted_information": extracted.data if extracted else {},
        "verification_results": [
            {
                "field": v.field_name,
                "extracted_value": v.extracted_value,
                "confidence": v.confidence,
                "evidence_page": v.evidence_page,
            }
            for v in verifications
        ],
        "risk_analysis": [
            {
                "risk": r.risk_title,
                "risk_level": r.risk_level,
                "explanation": r.explanation,
                "evidence": r.evidence,
                "recommended_action": r.recommended_action,
                "possible_resolution": r.possible_resolution,
            }
            for r in risks
        ],
        "overall_risk_summary": {
            "high_count": counts["HIGH"],
            "medium_count": counts["MEDIUM"],
            "low_count": counts["LOW"],
            "overall": overall_risk,
        },
        "disclaimer": (
            "This report is generated by an AI-assisted document analysis system. "
            "It does not constitute legal advice and does not determine legal validity "
            "of the property or document. All findings require verification by a "
            "qualified legal professional before any decision is made."
        ),
    }
